apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.embedsaveopenai.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.embedsaveopenai.name}}
spec:
  replicas: {{.Values.embedsaveopenai.replicas}}
  selector:
    matchLabels:
      app: {{.Values.embedsaveopenai.name}}
  template:
    metadata:
      labels:
        app: {{.Values.embedsaveopenai.name}}
    spec:
      containers:
        - name: {{.Values.embedsaveopenai.name}}
          image: "{{ .Values.embedsaveopenai.image.repository }}:{{ .Values.embedsaveopenai.image.tag }}"
          imagePullPolicy: {{.Values.embedsaveopenai.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.embedsaveopenai.service.port}}
          env:
            - name: GO_ENV
              value: "{{ .Values.embedsaveopenai.GO_ENV }}"
            - name: SERVER_PORT
              value: "{{ .Values.embedsaveopenai.SERVER_PORT }}"
            - name: WORKER_NAME
              value: "{{ .Values.embedsaveopenai.WORKER_NAME }}"
            - name: NATS_URL
              value: "{{ .Values.embedsaveopenai.NATS_URL }}"
            - name: NATS_DLQ_SUBJECT
              value: "{{ .Values.embedsaveopenai.NATS_DLQ_SUBJECT }}"
            - name: STREAM
              value: "{{ .Values.embedsaveopenai.STREAM }}"
            - name: SUBJECTS
              value: "{{ .Values.embedsaveopenai.SUBJECTS }}"
            - name: REPLY_SUBJECT
              value: "{{ .Values.embedsaveopenai.REPLY_SUBJECT }}"
            - name: MAX_DELIVERY_ATTEMPTS
              value: "{{ .Values.embedsaveopenai.MAX_DELIVERY_ATTEMPTS }}"
            - name: PUBLIC_GATEWAY_URL
              value: "{{ .Values.embedsaveopenai.PUBLIC_GATEWAY_URL }}"
            - name: RECORD_SERVICE_URL
              value: "{{ .Values.embedsaveopenai.RECORD_SERVICE_URL }}"
            - name: SERVICE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-auth-token
                  key: service-auth-token
