apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.embedcreateimageopenai.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.embedcreateimageopenai.name}}
spec:
  replicas: {{.Values.embedcreateimageopenai.replicas}}
  selector:
    matchLabels:
      app: {{.Values.embedcreateimageopenai.name}}
  template:
    metadata:
      labels:
        app: {{.Values.embedcreateimageopenai.name}}
    spec:
      containers:
        - name: {{.Values.embedcreateimageopenai.name}}
          image: "{{ .Values.embedcreateimageopenai.image.repository }}:{{ .Values.embedcreateimageopenai.image.tag }}"
          imagePullPolicy: {{.Values.embedcreateimageopenai.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.embedcreateimageopenai.service.port}}
          env:
            - name: GO_ENV
              value: "{{ .Values.embedcreateimageopenai.GO_ENV }}"
            - name: SERVER_PORT
              value: "{{ .Values.embedcreateimageopenai.SERVER_PORT }}"
            - name: WORKER_NAME
              value: "{{ .Values.embedcreateimageopenai.WORKER_NAME }}"
            - name: NATS_URL
              value: "{{ .Values.embedcreateimageopenai.NATS_URL }}"
            - name: NATS_DLQ_SUBJECT
              value: "{{ .Values.embedcreateimageopenai.NATS_DLQ_SUBJECT }}"
            - name: STREAM
              value: "{{ .Values.embedcreateimageopenai.STREAM }}"
            - name: SUBJECTS
              value: "{{ .Values.embedcreateimageopenai.SUBJECTS }}"
            - name: REPLY_SUBJECT
              value: "{{ .Values.embedcreateimageopenai.REPLY_SUBJECT }}"
            - name: MAX_DELIVERY_ATTEMPTS
              value: "{{ .Values.embedcreateimageopenai.MAX_DELIVERY_ATTEMPTS }}"
            - name: EAK_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: eak-encryption-key
                  key: eak-encryption-key
