apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.externalapikey.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.externalapikey.name}}
spec:
  replicas: {{.Values.externalapikey.replicas}}
  selector:
    matchLabels:
      app: {{.Values.externalapikey.name}}
  template:
    metadata:
      labels:
        app: {{.Values.externalapikey.name}}
    spec:
      containers:
        - name: {{.Values.externalapikey.name}}
          image: "{{ .Values.externalapikey.image.repository }}:{{ .Values.externalapikey.image.tag }}"
          imagePullPolicy: {{.Values.externalapikey.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.externalapikey.service.port}}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: database-url
            - name: EAK_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: eak-encryption-key
                  key: eak-encryption-key
            - name: SERVICE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-auth-token
                  key: service-auth-token
