apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.externalapikey.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.externalapikey.name}}
spec:
  replicas: {{.Values.externalapikey.replicas}}
  selector:
    matchLabels:
      app: {{.Values.externalapikey.name}}
  template:
    metadata:
      labels:
        app: {{.Values.externalapikey.name}}
    spec:
      containers:
        - name: {{.Values.externalapikey.name}}
          image: "{{ .Values.externalapikey.image.repository }}:{{ .Values.externalapikey.image.tag }}"
          imagePullPolicy: {{.Values.externalapikey.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.externalapikey.service.port}}
          env:
            - name: GO_ENV
              value: "{{ .Values.externalapikey.GO_ENV }}"
            - name: SERVER_PORT
              value: "{{ .Values.externalapikey.SERVER_PORT }}"
            - name: NATS_URL
              value: "{{ .Values.externalapikey.NATS_URL }}"
            - name: NATS_CLIENT_NAME
              value: "{{ .Values.externalapikey.NATS_CLIENT_NAME }}"
            - name: KEYCLOAK_URL
              value: "{{ .Values.externalapikey.KEYCLOAK_URL }}"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.externalapikey.KEYCLOAK_REALM }}"
            - name: PUBLIC_GATEWAY_URL
              value: "{{ .Values.externalapikey.PUBLIC_GATEWAY_URL }}"
            - name: USER_SERVICE_URL
              value: "{{ .Values.externalapikey.USER_SERVICE_URL }}"
            - name: RECORD_SERVICE_URL
              value: "{{ .Values.externalapikey.RECORD_SERVICE_URL }}"
            - name: EXTERNAL_API_KEY_SERVICE_URL
              value: "{{ .Values.externalapikey.EXTERNAL_API_KEY_SERVICE_URL }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: database-url
            - name: EAK_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: eak-encryption-key
                  key: eak-encryption-key
            - name: SERVICE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-auth-token
                  key: service-auth-token
