apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.gateway.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.gateway.name}}
spec:
  replicas: {{.Values.gateway.replicas}}
  selector:
    matchLabels:
      app: {{.Values.gateway.name}}
  template:
    metadata:
      labels:
        app: {{.Values.gateway.name}}
    spec:
      containers:
        - name: {{.Values.gateway.name}}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{.Values.gateway.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.gateway.service.port}}
          env:
            - name: GO_ENV
              value: "{{ .Values.gateway.GO_ENV }}"
            - name: SERVER_PORT
              value: "{{ .Values.gateway.SERVER_PORT }}"
            - name: AUTH_PAT_CONTROL_CHAR
              value: "{{ .Values.gateway.AUTH_PAT_CONTROL_CHAR }}"
            - name: KEYCLOAK_URL
              value: "{{ .Values.gateway.KEYCLOAK_URL }}"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.gateway.KEYCLOAK_REALM }}"
            - name: PUBLIC_GATEWAY_URL
              value: "{{ .Values.gateway.PUBLIC_GATEWAY_URL }}"
            - name: EXTERNAL_API_KEY_SERVICE_URL
              value: "{{ .Values.gateway.EXTERNAL_API_KEY_SERVICE_URL }}"
            - name: RECORD_SERVICE_URL
              value: "{{ .Values.gateway.RECORD_SERVICE_URL }}"
            - name: USER_SERVICE_URL
              value: "{{ .Values.gateway.USER_SERVICE_URL }}"
            - name: SERVICE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-auth-token
                  key: service-auth-token
