apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.keycloak.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.keycloak.name}}
spec:
  replicas: {{.Values.keycloak.replicas}}
  selector:
    matchLabels:
      app: {{.Values.keycloak.name}}
  template:
    metadata:
      labels:
        app: {{.Values.keycloak.name}}
    spec:
      containers:
        - name: {{.Values.keycloak.name}}
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{.Values.keycloak.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.keycloak.service.port}}
            - containerPort: {{.Values.keycloak.service.adminDashboardPort}}
            - containerPort:
                {{.Values.keycloak.service.otherAdminDashboardPort}}
          env:
            - name: KC_DB
              value: "{{ .Values.keycloak.KC_DB }}"
            - name: KC_DB_SCHEMA
              value: "{{ .Values.keycloak.KC_DB_SCHEMA }}"
            - name: KC_PROXY
              value: "{{ .Values.keycloak.KC_PROXY }}"
            - name: KC_HTTP_ENABLED
              value: "{{ .Values.keycloak.KC_HTTP_ENABLED }}"
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.keycloak.KEYCLOAK_ADMIN }}"
            - name: KC_HOSTNAME
              value: "{{ .Values.keycloak.KC_HOSTNAME }}"
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: kc-db-url
                  key: kc-db-url
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-db-password
                  key: kc-db-password
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-db-admin-password
                  key: kc-db-admin-password
