apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.nats.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.nats.name}}
spec:
  replicas: {{.Values.nats.replicas}}
  selector:
    matchLabels:
      app: {{.Values.nats.name}}
  template:
    metadata:
      labels:
        app: {{.Values.nats.name}}
    spec:
      containers:
        - name: {{.Values.nats.name}}
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{.Values.nats.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.nats.service.port}}
            - containerPort: {{.Values.nats.service.mgmtPort}}
          env:
            - name: NATS_LOG_LEVEL
              value: "{{ .Values.nats.NATS_LOG_LEVEL }}"
