apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.user.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.user.name}}
spec:
  replicas: {{.Values.user.replicas}}
  selector:
    matchLabels:
      app: {{.Values.user.name}}
  template:
    metadata:
      labels:
        app: {{.Values.user.name}}
    spec:
      containers:
        - name: {{.Values.user.name}}
          image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}"
          imagePullPolicy: {{.Values.user.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.user.service.port}}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: database-url
            - name: GO_ENV
              value: "{{ .Values.user.GO_ENV }}"
            - name: SERVER_PORT
              value: "{{ .Values.user.SERVER_PORT }}"
            - name: GATEWAY_URL
              value: "{{ .Values.user.GATEWAY_URL }}"
            - name: USER_SERVICE_URL
              value: "{{ .Values.user.USER_SERVICE_URL }}"
            - name: KEYCLOAK_URL
              value: "{{ .Values.user.KEYCLOAK_URL }}"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.user.KEYCLOAK_REALM }}"
