# You are editing:
# DEVELOPMENT
namespace: development
frontend:
  name: frontend
  replicas: 1
  image:
    repository: alo42/frontend
    pullPolicy: Always
    tag: development-1.0.3
  service:
    name: frontend
    port: 3000
  PORT: 3000
  CLOUD_URL: "http://api:3001"
  DATABASE_URL: "/var/data/db1.db"
api:
  name: api
  replicas: 1
  image:
    repository: alo42/api
    pullPolicy: Always
    tag: development-1.0.3
  service:
    name: api
    port: 3001
  PORT: 3001
  COMMONBASE_PLATFORM_URL: 'https://yourcommonbase.com/gateway'
  SUPABASE_COMMONBASE_TABLE: "ycb_staging"
  SUPABASE_COMMONBASE_RANDOM_RPC: "random_rows_ycb_staging"
  MATCH_THRESHOLD_DEFAULT: "0.2"
  MATCH_LIMIT_DEFAULT: "3"
  FTS_INDEX_NAME: ycb_fts_staging
gateway:
  name: gateway
  replicas: 1
  image:
    repository: alo42/gateway
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: gateway
    port: 5003
  GO_ENV: development
  SERVER_PORT: 5003
  AUTH_PAT_CONTROL_CHAR: ycb
  KEYCLOAK_URL: "keycloak:8080"
  KEYCLOAK_REALM: ycb
  PUBLIC_GATEWAY_URL: "https://yourcommonbase.com/gateway"
  EXTERNAL_API_KEY_SERVICE_URL: "externalapikey:5000"
  RECORD_SERVICE_URL: "record:5001"
  USER_SERVICE_URL: "user:5002"
user:
  name: user
  replicas: 1
  image:
    repository: alo42/user
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: user
    port: 5002
  GO_ENV: development
  SERVER_PORT: 5002
  GATEWAY_URL: gateway:5003
  USER_SERVICE_URL: user:5002
  KEYCLOAK_URL: keycloak:8080 
  KEYCLOAK_REALM: ycb
record:
  name: record
  replicas: 1
  image:
    repository: alo42/record
    pullPolicy: Always
    tag: development-1.0.1
  service:
    name: record
    port: 5001
  GO_ENV: development
  SERVER_PORT: 5001
  RECORD_IMAGE_BUCKET: 'ycb-development'
  AWS_REGION: us-east-2
  KEYCLOAK_URL: "keycloak:8080"
  KEYCLOAK_REALM: ycb
  SEARCH_DEFAULT_MATCH_LIMIT: "10"
  SEARCH_DEFAULT_MATCH_THRESHOLD: "0.2"
  PUBLIC_GATEWAY_URL: "https://yourcommonbase.com/gateway"
  USER_SERVICE_URL: "user:5002"
  RECORD_SERVICE_URL: "record:5001"
  NATS_URL: "nats://nats:4222"
  NATS_CLIENT_NAME: "record"
  NATS_DLQ: "dlq"
  NATS_CREATE_IMAGE_OPENAI_SUBJECT: "embed.create.img.openai"
  NATS_CREATE_TEXT_OPENAI_SUBJECT: "embed.create.text.openai"
  NATS_CREATE_STREAM: "NATS_CREATE_STREAM"
  NATS_SAVE_STREAM: "NATS_SAVE_STREAM"
  NATS_SAVE_OPENAI_SUBJECT: "embed.save.openai"
externalapikey:
  name: externalapikey
  replicas: 1
  image:
    repository: alo42/external-api-key
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: externalapikey
    port: 5000
  GO_ENV: development
  SERVER_PORT: 5000
  NATS_URL: "nats://nats:4222"
  NATS_CLIENT_NAME: "external-api-key"
  KEYCLOAK_URL: "keycloak:8080"
  KEYCLOAK_REALM: ycb
  PUBLIC_GATEWAY_URL: "https://yourcommonbase.com/gateway"
  USER_SERVICE_URL: "user:5002"
  RECORD_SERVICE_URL: "record:5001"
  EXTERNAL_API_KEY_SERVICE_URL: "externalapikey:5000"
keycloak:
  name: keycloak
  replicas: 1
  image:
    repository: alo42/keycloak
    pullPolicy: Always
    tag: development-1.0.5
  service:
    name: keycloak
    port: 8080
    adminDashboardPort: 9000
    otherAdminDashboardPort: 8443
  KC_DB: postgres
  KC_DB_SCHEMA: keycloak
  KC_PROXY: edge
  KC_HTTP_ENABLED: "true"
  KEYCLOAK_ADMIN: admin
  KC_HOSTNAME: 'https://yourcommonbase.com/keycloak'
  KC_LOG_LEVEL: debug
nats:
  name: nats
  replicas: 1
  image:
    repository: alo42/nats
    pullPolicy: Always
    tag: development-1.0.1
  service:
    name: nats
    port: 4222
    mgmtPort: 8222
  NATS_LOG_LEVEL: debug
embedcreateimageopenai:
  name: embedcreateimageopenai
  replicas: 1
  image:
    repository: alo42/embed-create-image-openai
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: embedcreateimageopenai
    port: 5005
  SERVER_PORT: 5005
  GO_ENV: development
  WORKER_NAME: "embed-create-image-openai-worker"
  NATS_URL: "nats://nats:4222"
  NATS_DLQ_SUBJECT: "dlq"
  REPLY_SUBJECT: "embed.save.openai"
  SUBJECTS: "embed.create.img.openai"
  STREAM: "embedding-create-stream"
  MAX_DELIVERY_ATTEMPTS: 5
embedcreatetextopenai:
  name: embedcreatetextopenai
  replicas: 1
  image:
    repository: alo42/embed-create-text-openai
    pullPolicy: Always
    tag: development-1.0.3
  service:
    name: embedcreatetextopenai
    port: 5006
  SERVER_PORT: 5006
  GO_ENV: development
  WORKER_NAME: "embed-create-text-openai-worker"
  NATS_URL: "nats://nats:4222"
  NATS_DLQ_SUBJECT: "dlq"
  REPLY_SUBJECT: "embed.save.openai"
  SUBJECTS: "embed.create.text.openai"
  STREAM: "embedding-create-stream"
  MAX_DELIVERY_ATTEMPTS: 5
  PUBLIC_GATEWAY_URL: "https://yourcommonbase.com/gateway"
  RECORD_SERVICE_URL: "record:5001"
embedsaveopenai:
  name: embedsaveopenai
  replicas: 1
  image:
    repository: alo42/embed-save-openai
    pullPolicy: Always
    tag: development-1.0.2
  service:
    port: 5007
  GO_ENV: development
  SERVER_PORT: 5007
  WORKER_NAME: "embed-save-openai-worker"
  NATS_URL: "nats://nats:4222"
  NATS_DLQ_SUBJECT: "dlq"
  SUBJECTS: "embed.save.openai"
  STREAM: "embedding-save-stream"
  MAX_DELIVERY_ATTEMPTS: 5
  PUBLIC_GATEWAY_URL: "https://yourcommonbase.com/gateway"
  RECORD_SERVICE_URL: "record:5001"
ingress:
  name: ycb-development
  ingressClassName: nginx
  host: yourcommonbase.com
