# You are editing:
# DEVELOPMENT
namespace: development
frontend:
  name: frontend
  replicas: 1
  image:
    repository: alo42/frontend
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: frontend
    port: 3000
  PORT: 3000
api:
  name: api
  replicas: 1
  image:
    repository: alo42/api
    pullPolicy: Always
    tag: development-1.0.2
  service:
    name: api
    port: 3001
  PORT: 3001
  COMMONBASE_PLATFORM_URL: 'https://development.yourcommonbase.com/gateway'
  SUPABASE_COMMONBASE_TABLE: "ycb_staging"
  SUPABASE_COMMONBASE_RANDOM_RPC: "random_rows_ycb_staging"
  MATCH_THRESHOLD_DEFAULT: "0.2"
  MATCH_LIMIT_DEFAULT: "3"
  FTS_INDEX_NAME: ycb_fts_staging
gateway:
  name: gateway
  replicas: 1
  image:
    repository: alo42/gateway
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: gateway
    port: 5003
  GO_ENV: development
  SERVER_PORT: 5003
  AUTH_PAT_CONTROL_CHAR: ycb
  KEYCLOAK_URL: "keycloak:8080"
  KEYCLOAK_REALM: ycb
  PUBLIC_GATEWAY_URL: "https://development.yourcommonbase.com/gateway"
  EXTERNAL_API_KEY_SERVICE_URL: "externalapikey:5000"
  RECORD_SERVICE_URL: "record:5001"
  USER_SERVICE_URL: "user:5002"
user:
  name: user
  replicas: 1
  image:
    repository: alo42/user
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: user
    port: 5002
  GO_ENV: development
  SERVER_PORT: 5002
  GATEWAY_URL: gateway:5003
  USER_SERVICE_URL: user:5002
  KEYCLOAK_URL: keycloak:8080 
  KEYCLOAK_REALM: ycb
record:
  name: record
  replicas: 1
  image:
    repository: alo42/record
    pullPolicy: Always
    tag: development-1.0.1
  service:
    name: record
    port: 5001
  GO_ENV: development
  SERVER_PORT: 5001
  RECORD_IMAGE_BUCKET: 'ycb-development'
  AWS_REGION: us-east-2
  NATS_URL: "nats://nats:4222"
  NATS_CLIENT_NAME: "record"
  NATS_DLQ: "dlq"
  NATS_CREATE_STREAM: "NATS_CREATE_STREAM"
  NATS_SAVE_STREAM: "NATS_SAVE_STREAM"
  NATS_SAVE_OPENAI_SUBJECT: "embed.save.openai"
  KEYCLOAK_URL: "keycloak:8080"
  KEYCLOAK_REALM: ycb
  SEARCH_DEFAULT_MATCH_LIMIT: "10"
  SEARCH_DEFAULT_MATCH_THRESHOLD: "0.2"
  PUBLIC_GATEWAY_URL: "https://development.yourcommonbase.com/gateway"
  USER_SERVICE_URL: "user:5002"
  RECORD_SERVICE_URL: "record:5001"
  NATS_CREATE_IMAGE_OPENAI_SUBJECT: "embed.create.img.openai"
  NATS_CREATE_TEXT_OPENAI_SUBJECT: "embed.create.text.openai"
externalapikey:
  name: externalapikey
  replicas: 1
  image:
    repository: alo42/external-api-key
    pullPolicy: Always
    tag: development-1.0.0
  service:
    name: externalapikey
    port: 5000
  GO_ENV: development
  SERVER_PORT: 5000
  NATS_URL: "nats://nats:4222"
  NATS_CLIENT_NAME: "external-api-key"
  KEYCLOAK_URL: "keycloak:8080"
  KEYCLOAK_REALM: ycb
  PUBLIC_GATEWAY_URL: "https://development.yourcommonbase.com/gateway"
  USER_SERVICE_URL: "user:5002"
  RECORD_SERVICE_URL: "record:5001"
  EXTERNAL_API_KEY_SERVICE_URL: "externalapikey:5000"
keycloak:
  name: keycloak
  replicas: 1
  image:
    repository: alo42/keycloak
    pullPolicy: Always
    tag: latest
  service:
    name: keycloak
    port: 8080
  KC_DB: keycloak
  KC_DB_SCHEMA: keycloak
  KC_PROXY: edge
  KC_HTTP_ENABLED: "true"
  KEYCLOAK_ADMIN: admin
nats:
  name: nats
  replicas: 1
  image:
    repository: nats
    pullPolicy: Always
    tag: latest
  service:
    name: nats
    port: 4222
ingress:
  name: ycb-development
  ingressClassName: nginx
  host: development.yourcommonbase.com
