apiVersion: v1
kind: Service
metadata:
  name: {{.Values.nats.service.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.nats.service.name}}
spec:
  type:
  ports:
    - name: nats
      port: {{.Values.nats.service.port}}
      targetPort: {{.Values.nats.service.port}}
    - name: nats-mgmt
      port: {{.Values.nats.service.mgmtPort}}
      targetPort: {{.Values.nats.service.mgmtPort}}
  selector:
    app: {{.Values.nats.service.name}}
