apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingress.name}}
  namespace: {{.Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 6m
spec:
  ingressClassName: {{.Values.ingress.ingressClassName}}
  rules:
    - host: {{.Values.ingress.drmHost}}
      http:
        paths:
          - path: /backend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.api.service.name}}
                port:
                  number: {{.Values.api.service.port}}
          - path: /external-api-key(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.externalapikey.service.name}}
                port:
                  number: {{.Values.externalapikey.service.port}}
          - path: /gateway(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.gateway.service.name}}
                port:
                  number: {{.Values.gateway.service.port}}
          - path: /record(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.record.service.name}}
                port:
                  number: {{.Values.record.service.port}}
          - path: /user(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.user.service.name}}
                port:
                  number: {{.Values.user.service.port}}
          - path: /keycloak(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.keycloak.service.name}}
                port:
                  number: {{.Values.keycloak.service.port}}
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{.Values.frontend.service.name}}
                port:
                  number: {{.Values.frontend.service.port}}
